project_name: react-boss
project_description: 'Boss implementation in react app'
repository_url: 'https://github.com/badyakarprabin/react-boss'
branch_url: 'https://github.com/badyakarprabin/react-boss/tree/master'
user: #The user used to access the servers through SSH.
port: #The port used to access the servers through SSH.
deployment:
  web:
    build_dir: build/
    base_dir: /source/app/deployment/frontend
    keep_builds: 10

stages:
  dev:
    host: #Address of the hosted server for the defined stage.
    public_url: #The public url to access this website.
    logging:
      files:
        - /source/app/logs/access.log
        - /source/app/logs/error.log

scripts:
  install: 'yarn'
  build: 'yarn build'

notifications:
  slack:
    enabled: true
    endpoint: ${BOSS_SLACK_ENDPOINT}

  hipchat:
    enabled: true
    notify: true
    company_name: ${BOSS_HIPCHAT_COMPANY}
    room_id: ${BOSS_HIPCHAT_ROOM}
    auth_token: ${BOSS_HIPCHAT_TOKEN}
